/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProcessTiktokRouteImport } from './routes/api/process-tiktok'
import { Route as ApiProcessTiktokJobIdRouteImport } from './routes/api/process-tiktok.$jobId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessTiktokRoute = ApiProcessTiktokRouteImport.update({
  id: '/api/process-tiktok',
  path: '/api/process-tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessTiktokJobIdRoute = ApiProcessTiktokJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiProcessTiktokRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/process-tiktok': typeof ApiProcessTiktokRouteWithChildren
  '/api/process-tiktok/$jobId': typeof ApiProcessTiktokJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/process-tiktok': typeof ApiProcessTiktokRouteWithChildren
  '/api/process-tiktok/$jobId': typeof ApiProcessTiktokJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/process-tiktok': typeof ApiProcessTiktokRouteWithChildren
  '/api/process-tiktok/$jobId': typeof ApiProcessTiktokJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/process-tiktok'
    | '/api/process-tiktok/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/api/process-tiktok' | '/api/process-tiktok/$jobId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/process-tiktok'
    | '/api/process-tiktok/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ApiProcessTiktokRoute: typeof ApiProcessTiktokRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process-tiktok': {
      id: '/api/process-tiktok'
      path: '/api/process-tiktok'
      fullPath: '/api/process-tiktok'
      preLoaderRoute: typeof ApiProcessTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process-tiktok/$jobId': {
      id: '/api/process-tiktok/$jobId'
      path: '/$jobId'
      fullPath: '/api/process-tiktok/$jobId'
      preLoaderRoute: typeof ApiProcessTiktokJobIdRouteImport
      parentRoute: typeof ApiProcessTiktokRoute
    }
  }
}

interface ApiProcessTiktokRouteChildren {
  ApiProcessTiktokJobIdRoute: typeof ApiProcessTiktokJobIdRoute
}

const ApiProcessTiktokRouteChildren: ApiProcessTiktokRouteChildren = {
  ApiProcessTiktokJobIdRoute: ApiProcessTiktokJobIdRoute,
}

const ApiProcessTiktokRouteWithChildren =
  ApiProcessTiktokRoute._addFileChildren(ApiProcessTiktokRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ApiProcessTiktokRoute: ApiProcessTiktokRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
